# Esquema para o projeto Ceconi3D

# Tabela de Usuários
type User @table {
  id: String! @default(expr: "auth.uid")
  email: String! @col(dataType: "varchar(100)")
  name: String
  createdAt: Timestamp! @default(expr: "request.time")
}
